### ISSUE TITLE
Pull activity_regularizer value and final activation function up as parameters in feedforward_model

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#127] opened 2019-02-21 14:03 UTC
Today they are hardcoded as "regularizers.l1(10e-5)" and "tanh", but should be parameters.

**Comment by epa095** [comment] 2019-08-08 08:57
Same as #378?

**Comment by ryanjdillon** [comment] 2019-08-26 05:53
Optimizer args are exposed in PR #429

**Comment by ryanjdillon** [comment] 2019-08-26 08:39
`tanh` appears to already be in place. `regularizers.l1(10e-5)` will be included in the exposing of other regularizer parameters that can be passed as args.

**Comment by ryanjdillon** [comment] 2019-08-26 09:33
As per Natalie, should we remove the accuracy metric since it is not applicable to a regression type problems.

**Comment by ryanjdillon** [comment] 2019-08-29 12:25
If we want all available regularization methods from `keras`, it won't be possible to pass things EXACTLY as we do with the optimizer (i.e. `optimizer="adam"` and `optimizer_kwargs={}`), but we could do it fairly similar as shown below. 

Does this look ok @epa095?

Explanation `keras` of regularizer types:
https://stats.stackexchange.com/a/383326/16938

Example pseudo implementation:
```python
# config
regularizer_config = {
    "activity_regularlizer": {
        "l1": 0.1
        },
    "kernel_regularizer": {
        "l1_l2": {
            "l1": 0.1,
            "l2": 0.2}
        },
    "bias_regularlizer": {
        "l1": 0.1
        },
    "recurrent_regularlizer": {
        "l1": 0.1
        },
}

# model parameter
def lstm_model(
        regularizer: Dict = {},
        ):
    model = kerar.model()
    args = {...}
    for i, (units, activation) in enumerate(zip(encoding_dim, encoding_func)):
        args.update(**regularizer_args)
        model.add(Dense(**args))

    return model
```
The feed forward doesn't have the `recurrent_regularizer` method, so we could issue a warning if extra option is passed to it or something.

**Comment by ryanjdillon** [comment] 2019-08-30 05:06
> hi ryan i spoke with Eric about the regularizations...it should be doable although it can get ugly,
but we should do it in such a way that the case when regularization is applied to all weights, it is implemented in an easy way in the config.
in the other case when regularization is implemented on some layers, maybe we could use a dict where the keys represent the layer that we want to apply regularization on
and the value is the factor that controls the level of the regularization term

**Comment by ryanjdillon** [comment] 2019-09-02 08:21
It sounds like the current suggestion is that the regularizer parameter could take both (1) a basic format that applies a single regularizer to all layers for quick and general use and (2) a tuple of detailed configurations with a config for each layer.

i.e. ...
1. Example for an n-layer network with same regularization applied per layer
```python
regularizer = ("l1", 0.1)
# alternatively
regularizer = {"activity_regularlizer": {"l1": 0.1},}
```
2.  Example for a 3-layer network, with varying regularization applied per layer
```python
regularizer = (
    {"activity_regularlizer": {"l1": 0.1},  "recurrent_regularlizer": {"l1": 0.1}}, # layer1
    {"bias_regularlizer": {"l1": 0.1}, "recurrent_regularlizer": {"l1": 0.1}}, # layer2
    {"recurrent_regularlizer": {"l1": 0.1}} # layer3
)
```
@Natalie-Caruana @epa095 Is this what you all are envision? Perhaps the input/output layers need to have their own configs in (2) is well. I'll check on that before commencement of this here change.

**Comment by ryanjdillon** [comment] 2019-09-02 11:37
The different use-cases we discussed that would require some different level of regularization configurations were:
1.  Default call, assume one type of reg. (e.g. "activity_reg", "l1", 0.1)
2.  Customize for all layers (e.g. "bias_reg" not "activity_reg" for all)
3. Customize for some layers

Doing things as per 1b and 2 would allow for th

Natalie and I discussed the possibility of specifying the regularization config for only a specific set of layers to avoid having long lists of configurations, which could also apply to the `*_dim` and `*_func` parameters.

To do this you'd need to specify the layers somehow, e.g. :
```python
regularizers = (
    {"layers": [0,1,8], "config": {"activity_regularlizer": {"l1": 0.1}}},
    ...,
)
```

**Comment by Natalie-Caruana** [comment] 2019-09-02 13:06
I think its a good idea to specify regularization for some layers in this way
```regularizers = ( {"layers": [0,1,8], "config": {"activity_regularlizer": {"l1": 0.1}}},...)```
as otherwise we would have to list all the layers even those that have not any regularization implemented on. 
With regards to implementing regularization for all layers, I think we should have some sensible values for the default regularizer and for the customized regularizer have something like this:
```regularizer = {"activity_regularizer": {"l1": 0.1}}```

**Closed as completed** 2020-01-28 10:51 UTC
Labels: good first issue, wontfix
