### ISSUE TITLE
Grafana dashboard showing wrong tags

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#372] opened 2019-07-11 12:02 UTC
Reproduce:
- With a new gordo-deploy, build the project equinor/gordo-test-project 
- The sfb model has two tags - but the legend shows all tags.

**Comment by alexisc67** [comment] 2019-07-11 13:39
The issue is on the variable $Sensor, it returns all the possible tags. There is no way to make it to inherit the filter on the $Machine variable. To fix you have to use the option "With Only Nulls" under "Legend" > "Hide Series" of the Graph. I have fixed in preprod

**Comment by SveinErikStokka** [comment] 2019-07-29 13:09
You can use this query for the $Sensor variable to filter on $Machine (with postgres-metadata as data source):

`SELECT jsonb_array_elements->>'name' as tag FROM machine, jsonb_array_elements(machine.metadata->'endpoint-metadata'->'metadata'->'dataset'->'tag_list') WHERE machine.name ='$Machine'
`

**Closed as completed** 2019-11-27 11:57 UTC
